apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: dev
spec:
  selector:
    app: portfolio-service
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30003
  type: NodePort
