version: "3.9"
services:
  order-service:
    build: ./services/order-service
    env_file:
      - ./services/order-service/.env
    ports:
      - "8000:8000"
    depends_on:
      - order-db

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

volumes:
  order-db-data:
