pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "aadideshpande1/quant-trading-platform-portfolio-service"
    }

    stages {
        stage('Build') {
            steps {
                sh 'echo "Running build checks for Portfolio Service..."'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Running tests for Portfolio Service..."'
            }
        }

        stage('Security Scan') {
            steps {
                sh 'echo "Running static security analysis..."'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:${BUILD_NUMBER} ./services/portfolio-service'
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $DOCKER_IMAGE:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying Portfolio Service build ${BUILD_NUMBER}..."
            }
        }
    }
}
